import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'fr' | 'ru' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dental': 'Dental',
    'nav.dental.implants': 'Dental Implant',
    'nav.dental.hollywood': 'Hollywood Smile',
    'nav.hair': 'Hair Transplant',
    'nav.hair.male': 'Male Hair Transplant',
    'nav.hair.female': 'Female Hair Transplant',
    'nav.hair.beard': 'Beard & Moustache Transplant',
    'nav.hair.eyebrow': 'Eyebrow Transplant',
    'nav.about': 'About Us',
    'nav.about.appointment': 'Appointment',
    'nav.about.blog': 'Blog',
    'nav.about.contact': 'Contact Us',
    'nav.articles': 'Articles',
    'nav.doctors': 'Our Doctors',
    'nav.booking': 'Book Now',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Transform Your Life with Premium Medical Care',
    'hero.subtitle': 'Because Teeth Have Feelings Too. Enjoy Specialized Care Through Precision, Artistry, And Experience.',
    'hero.cta': 'Schedule Consultation',
    'hero.subheader': 'Premium Medical Tourism',
    'hero.watchTour': 'Watch Clinic Tour',
    
    // Stats
    'stats.patients': 'Happy Patients',
    'stats.years': 'Years of Excellence',
    'stats.success': 'Success Rate',
    'stats.countries': 'Countries Served',
    
    // Features
    'feature.title': 'Why Choose Us',
    'feature.subtitle': 'World-class care, affordable excellence — all in one destination.',
    'feature.1.title': 'Expert Specialists',
    'feature.1.desc': 'Board-certified doctors with international experience.',
    'feature.2.title': 'Modern Facilities',
    'feature.2.desc': 'State-of-the-art equipment and technology.',
    'feature.3.title': 'Artistry & Precision',
    'feature.3.desc': 'Tailored aesthetic designs for your unique features.',
    'feature.4.title': 'All-Inclusive Packages',
    'feature.4.desc': 'Treatment, accommodation, and transfers included.',

    // Home Treatments Section
    'home.treatments.title': 'Our Signature Treatments',
    'home.treatments.subtitle': 'Discover our most sought-after procedures, trusted by patients from 50+ countries',
    
    // Testimonials
    'testimonials.title': 'What Our Patients Say',
    'testimonials.1.text': 'Amazing experience! The staff was professional and the results exceeded my expectations. Highly recommend!',
    'testimonials.1.name': 'John Smith',
    'testimonials.1.treatment': 'Dental Implants',
    'testimonials.2.text': 'Best decision I ever made. The doctors were caring and the clinic was spotless. My smile has never looked better.',
    'testimonials.2.name': 'Sarah Johnson',
    'testimonials.2.treatment': 'Veneers',
    'testimonials.3.text': 'Incredible hair transplant results! Natural looking and the process was painless. Thank you!',
    'testimonials.3.name': 'Michael Brown',
    'testimonials.3.treatment': 'FUE Hair Transplant',
    'testimonials.subtitle': 'Thousands of patients trust us every year',
    
    // Home CTA
    'home.cta.title': 'Ready to Transform Your Life?',
    'home.cta.subtitle': 'Schedule your free consultation today and discover the difference',

    // Dental Treatments
    'dental.title': 'Dental Treatments',
    'dental.subtitle': 'Comprehensive dental care with cutting-edge technology',
    'dental.implants': 'Dental Implants',
    'dental.implants.desc': 'Permanent tooth replacement solution with titanium implants.',
    'dental.implants.price': 'Contact us for pricing',
    'dental.whitening': 'Teeth Whitening',
    'dental.whitening.desc': 'Professional whitening for a brighter, confident smile.',
    'dental.whitening.price': 'Contact us for pricing',
    'dental.veneers': 'Porcelain / Emax Veneers',
    'dental.veneers.desc': 'Transform your smile with custom-made veneers and Hollywood Smile design.',
    'dental.veneers.price': 'Contact us for pricing',
    'dental.braces': 'Zirconia Crowns',
    'dental.braces.desc': 'High durability and natural-looking crowns for aesthetic restoration.',
    'dental.braces.price': 'Contact us for pricing',
    'dental.crowns': 'Lumineers',
    'dental.crowns.desc': 'Ultra-thin veneers for a seamless smile enhancement.',
    'dental.crowns.price': 'Contact us for pricing',
    'dental.rootcanal': 'Root Canal Treatment',
    'dental.rootcanal.desc': 'Pain-free root canal therapy to save your tooth.',
    'dental.rootcanal.price': 'Contact us for pricing',

    // Dental Treatment Keys (Used in Dental.tsx)
    'dental.treatment.implants.title': 'Dental Implants',
    'dental.treatment.implants.desc': 'Permanent tooth replacement solution with titanium implants and customized crowns.',
    'dental.treatment.whitening.title': 'Teeth Whitening',
    'dental.treatment.whitening.desc': 'Professional whitening for a brighter, confident smile using advanced laser technology.',
    'dental.treatment.veneers.title': 'Porcelain / Emax Veneers',
    'dental.treatment.veneers.desc': 'Transform your smile with custom-made veneers and Hollywood Smile design.',
    'dental.treatment.braces.title': 'Zirconia Crowns',
    'dental.treatment.braces.desc': 'High durability and natural-looking crowns for aesthetic restoration.',
    'dental.treatment.crowns.title': 'Lumineers',
    'dental.treatment.crowns.desc': 'Ultra-thin veneers for a seamless smile enhancement.',
    'dental.treatment.rootcanal.title': 'Root Canal Treatment',
    'dental.treatment.rootcanal.desc': 'Pain-free root canal therapy to save your natural tooth.',

    // Dental Features
    'dental.f.implants.1': 'Titanium implants',
    'dental.f.implants.2': 'Lifetime guarantee',
    'dental.f.implants.3': 'Painless procedure',
    'dental.f.implants.4': 'Natural appearance',
    'dental.f.whitening.1': 'Professional grade',
    'dental.f.whitening.2': 'Immediate results',
    'dental.f.whitening.3': 'Safe for enamel',
    'dental.f.whitening.4': '8-10 shades whiter',
    'dental.f.veneers.1': 'Custom-made porcelain',
    'dental.f.veneers.2': 'Stain-resistant',
    'dental.f.veneers.3': '15-20 year lifespan',
    'dental.f.veneers.4': 'Perfect alignment',
    'dental.f.braces.1': 'Metal or ceramic options',
    'dental.f.braces.2': 'Regular adjustments',
    'dental.f.braces.3': '12-24 month treatment',
    'dental.f.braces.4': 'Payment plans available',
    'dental.f.crowns.1': 'Zirconia or porcelain',
    'dental.f.crowns.2': 'Perfect color match',
    'dental.f.crowns.3': 'Durable materials',
    'dental.f.crowns.4': 'Two-visit procedure',
    'dental.f.rootcanal.1': 'Save natural tooth',
    'dental.f.rootcanal.2': 'Advanced microscopes',
    'dental.f.rootcanal.3': 'Pain-free treatment',
    'dental.f.rootcanal.4': 'High success rate',
    
    // Hair Treatments
    'hair.title': 'Hair Restoration',
    'hair.subtitle': 'Advanced hair transplant techniques for natural results',
    'hair.fue': 'Hair Transplant for Men',
    'hair.fue.desc': 'Moving healthy hair to bald areas under local anesthesia for permanent results.',
    'hair.fue.price': 'Contact us for pricing',
    'hair.dhi': 'DHI Hair Transplant',
    'hair.dhi.desc': 'Direct Hair Implantation for precise placement and maximum density.',
    'hair.dhi.price': 'Contact us for pricing',
    'hair.sapphire': 'Sapphire FUE',
    'hair.sapphire.desc': 'Advanced FUE with sapphire blades for faster healing.',
    'hair.sapphire.price': 'Contact us for pricing',
    'hair.prp': 'PRP Therapy',
    'hair.prp.desc': 'Platelet-rich plasma treatment to stimulate hair growth.',
    'hair.prp.price': 'Contact us for pricing',
    'hair.beard': 'Beard Transplant',
    'hair.beard.desc': 'Achieve a fuller, more defined beard with precision harvesting.',
    'hair.beard.price': 'Contact us for pricing',
    'hair.eyebrow': 'Eyebrow Transplant',
    'hair.eyebrow.desc': 'Natural-looking eyebrow restoration using advanced techniques.',
    'hair.eyebrow.price': 'Contact us for pricing',

    // Hair Treatment Keys (Used in Hair.tsx)
    'hair.treatment.fue.title': 'FUE Hair Transplant',
    'hair.treatment.fue.desc': 'Follicular Unit Extraction for natural results and maximum hair density.',
    'hair.treatment.dhi.title': 'DHI Hair Transplant',
    'hair.treatment.dhi.desc': 'Direct Hair Implantation for precise placement and faster recovery.',
    'hair.treatment.sapphire.title': 'Sapphire FUE',
    'hair.treatment.sapphire.desc': 'Advanced FUE using sapphire blades for minimal trauma and rapid healing.',
    'hair.treatment.prp.title': 'PRP Therapy',
    'hair.treatment.prp.desc': 'Platelet-rich plasma treatment to stimulate hair follicles and growth.',
    'hair.treatment.beard.title': 'Beard Transplant',
    'hair.treatment.beard.desc': 'Achieve a fuller, more defined beard with precision harvesting.',
    'hair.treatment.eyebrow.title': 'Eyebrow Transplant',
    'hair.treatment.eyebrow.desc': 'Natural-looking eyebrow restoration using advanced micro-grafting.',

    // Hair Features
    'hair.f.fue.1': '3000-5000 grafts',
    'hair.f.fue.2': 'No visible scarring',
    'hair.f.fue.3': 'Natural hairline design',
    'hair.f.fue.4': 'Minimally invasive',
    'hair.f.dhi.1': 'Choi implanter pen',
    'hair.f.dhi.2': 'Maximum density',
    'hair.f.dhi.3': 'Minimal handling',
    'hair.f.dhi.4': 'No incisions needed',
    'hair.f.sapphire.1': 'Sapphire blade technology',
    'hair.f.sapphire.2': 'Faster healing',
    'hair.f.sapphire.3': 'Less trauma',
    'hair.f.sapphire.4': 'High precision grafts',
    'hair.f.prp.1': 'Natural growth factors',
    'hair.f.prp.2': 'Non-surgical',
    'hair.f.prp.3': '3-6 sessions recommended',
    'hair.f.prp.4': 'Thicker hair',
    'hair.f.beard.1': '1500-3000 grafts',
    'hair.f.beard.2': 'Customized shape',
    'hair.f.beard.3': 'Natural direction',
    'hair.f.beard.4': 'Permanent results',
    'hair.f.eyebrow.1': '300-800 grafts',
    'hair.f.eyebrow.2': 'Natural arch',
    'hair.f.eyebrow.3': 'Precise placement',
    'hair.f.eyebrow.4': 'Subtle enhancement',

    // Hair Why
    'hair.why.1.title': 'Expert Surgeons',
    'hair.why.1.desc': '15+ years of experience in hair restoration',
    'hair.why.2.title': 'Advanced Techniques',
    'hair.why.2.desc': 'Latest FUE, DHI, and Sapphire methods',
    'hair.why.3.title': 'Natural Results',
    'hair.why.3.desc': '95%+ success rate with permanent outcomes',

    // Home Results
    'home.results.title': 'Real Results, Real Stories',
    'home.results.subtitle': 'Experience the transformation of our patients. We take pride in delivering natural, high-quality results that change lives.',
    'home.results.cta': 'View All Transformational Stories',
    'home.results.1.label': 'Digital Smile Design',
    'home.results.1.title': 'A Life-Changing Smile',
    'home.results.1.text': 'I was always self-conscious about my smile. The team at Gravity Clinic used the latest digital design technology to show me my future smile before we even started. The result is better than I ever imagined.',
    'home.results.1.category': 'Dental Aesthetics',
    'home.results.1.patient': 'Patient: Sarah M.',
    'home.results.2.label': 'Soft-FUE Hair Restoration',
    'home.results.2.title': 'Natural Hairline Restored',
    'home.results.2.text': 'Choosing Gravity Clinic for my hair transplant was the best decision. The FUE procedure was painless, and the recovery was remarkably fast. Six months later, and my hair looks completely natural.',
    'home.results.2.category': 'Hair Transplant',
    'home.results.2.patient': 'Patient: James L.',
    
    // Doctors
    'doctors.title': 'Meet Our Expert Team',
    'doctors.subtitle': 'International specialists dedicated to your care',
    
    // Booking
    'booking.title': 'Book Your Consultation',
    'booking.step1': 'Personal Information',
    'booking.step2': 'Treatment Selection',
    'booking.step3': 'Preferred Date',
    'booking.step4': 'Confirmation',
    'booking.firstName': 'First Name',
    'booking.lastName': 'Last Name',
    'booking.email': 'Email',
    'booking.phone': 'Phone Number',
    'booking.country': 'Country',
    'booking.treatment': 'Select Treatment',
    'booking.date': 'Preferred Date',
    'booking.message': 'Additional Information',
    'booking.next': 'Next',
    'booking.previous': 'Previous',
    'booking.submit': 'Submit Booking',
    
    // Contact
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'We\'re here to answer your questions',
    'contact.form.title': 'Send us a message',
    'contact.name': 'Your Name',
    'contact.subject': 'Subject',
    'contact.send': 'Send Message',
    'contact.locations': 'Our Locations',
    'contact.faq': 'Frequently Asked Questions',
    'contact.about': 'Gravity Clinic is a premier destination in Istanbul specializing in advanced dental and hair transplant treatments. Our expert team is dedicated to providing personalized care using state-of-the-art technology to achieve life-changing results with a focus on precision, artistry, and patient comfort.',
    
    // Articles
    'articles.hero.badge': 'Evidence-Based Medicine',
    'articles.hero.subtitle': 'Expert insights and clinical guides curated by the world\'s leading specialists.',
    'articles.filter.all': 'Volume: All',
    'articles.filter.dental': 'Specialty: Dental',
    'articles.filter.hair': 'Specialty: Hair',
    'articles.newsletter.badge': 'Insider Access',
    'articles.newsletter.title': 'Get Precision In Your Inbox',
    'articles.newsletter.subtitle': 'Join 5,000+ patients who receive monthly clinical pearls and breakthrough treatments from our specialists.',
    'articles.newsletter.cta': 'Join Exclusive List',
    
    // Common
    'common.restoration': 'Restoration',
    'common.learnMore': 'Learn More',
    'common.bookNow': 'Book Now',
    'common.readMore': 'Read More',
    'common.viewAll': 'View All',
    'common.features': 'Features',
    'common.pricing': 'Pricing',
    'common.gallery': 'Gallery',
    'common.years': 'Years Experience',
    'common.patients': 'Patients',
    'common.viewProfile': 'View Profile',
    'common.education': 'Education & Expertise',
    'common.languages': 'Languages',
    'common.successRate': 'Success Rate',
    'common.viewDetails': 'View Details',
    'common.whatsappSupport': 'Support on WhatsApp',
    'common.patientSatisfaction': 'Patient Satisfaction',
    'common.successfulResults': 'Successful Results',
    'common.duration': 'Duration',
    'common.procedure': 'Procedure',
    'common.appointments': 'Appointments',
    'common.oneDay': 'One Day',
    'common.hours': 'Hours',

    // Hero Badge
    'hero.clinic.badge': 'JCI Accredited International Clinic',

    // Doctors
    'doctors.sarah.specialty': 'Chief Dental Surgeon',
    'doctors.sarah.bio': 'Board-certified dental surgeon specializing in implants and cosmetic dentistry. Graduated from Harvard School of Dental Medicine.',
    'doctors.michael.specialty': 'Orthodontic Specialist',
    'doctors.michael.bio': 'Expert in modern orthodontics with focus on invisible aligners and accelerated treatment methods.',
    'doctors.ahmed.specialty': 'Hair Transplant Surgeon',
    'doctors.ahmed.bio': 'Pioneer in FUE and DHI techniques with thousands of successful hair transplants. International speaker and trainer.',
    'doctors.emily.specialty': 'Cosmetic Dentist',
    'doctors.emily.bio': 'Passionate about creating beautiful smiles through advanced cosmetic procedures and minimally invasive techniques.',
    'doctors.mehmet.specialty': 'Hair Restoration Expert',
    'doctors.mehmet.bio': 'Specialized in natural hairline design and high-density transplants. Member of ISHRS.',
    'doctors.lisa.specialty': 'Endodontist',
    'doctors.lisa.bio': 'Expert in root canal therapy and pain management using the latest microscopic techniques.',
    
    // Booking
    'booking.hero.subtitle': 'Your journey to a better you starts with a single step.',
    'booking.step1.desc': 'Please share your contact details for the VIP coordination.',
    'booking.step2.desc': 'Select the specialism you are interested in.',
    'booking.step3.desc': 'Choose your preferred arrival window.',
    'booking.step4.desc': 'Verify your information before finalizing.',
    'booking.success.title': 'Reservation Received',
    'booking.success.desc': 'Thank you, {name}. Our Patient Care Team will contact you within 2-4 business hours.',
    
    // Contact
    'contact.info.title': 'Get in Touch',
    'contact.info.desc': 'Have questions? Our friendly team is here to help. Reach out through any of these channels.',
    'contact.faq.subtitle': 'Common questions about our luxury medical journeys',
    'contact.workingHours': 'Working Hours',
    'contact.monSat': 'Monday - Saturday',
    'contact.sunday': 'Sunday',
    'contact.closed': 'Closed',
    
    // Footer
    'footer.expertise': 'Our Expertise',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'footer.desc': 'Setting the global standard in luxury medical tourism. Precision, art, and innovation in every procedure.',
    'footer.whatsapp': 'WhatsApp/Phone',
    'footer.istanbul': 'Istanbul Office',
    'footer.address': 'Nisantasi, Tesvikiye No: 42',
    'footer.hours': 'Clinic Hours',
    'footer.monSat': 'Mon - Sat',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2026 Gravity Clinic Global. All procedures are performed by certified medical professionals.',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.dental': 'Dentaire',
    'nav.dental.implants': 'Implant Dentaire',
    'nav.dental.hollywood': 'Sourire Hollywood',
    'nav.hair': 'Greffe de Cheveux',
    'nav.hair.male': 'Greffe Homme',
    'nav.hair.female': 'Greffe Femme',
    'nav.hair.beard': 'Greffe Barbe & Moustache',
    'nav.hair.eyebrow': 'Greffe Sourcils',
    'nav.about': 'À Propos',
    'nav.about.appointment': 'Rendez-vous',
    'nav.about.blog': 'Blog',
    'nav.about.contact': 'Contactez-nous',
    'nav.articles': 'Articles',
    'nav.doctors': 'Nos Médecins',
    'nav.booking': 'Réserver',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Transformez Votre Vie avec des Soins Médicaux Premium',
    'hero.subtitle': 'Parce que les Dents Ont Aussi des Sentiments. Profitez de Soins Spécialisés grâce à la Précision, l\'Art et l\'Expérience.',
    'hero.cta': 'Consultation Gratuite',
    'hero.subheader': 'Tourisme Médical Premium',
    'hero.watchTour': 'Voir la Visite de la Clinique',

    // Stats
    'stats.patients': 'Patients Heureux',
    'stats.years': 'Années d\'Excellence',
    'stats.success': 'Taux de Réussite',
    'stats.countries': 'Pays Desservis',
    
    // Features
    'feature.title': 'Pourquoi Nous Choisir',
    'feature.subtitle': 'Des soins de classe mondiale, une excellence abordable — tout en une destination.',
    'feature.1.title': 'Spécialistes Experts',
    'feature.1.desc': 'Médecins certifiés avec expérience internationale.',
    'feature.2.title': 'Installations Modernes',
    'feature.2.desc': 'Équipement et technologie de pointe.',
    'feature.3.title': 'Précision et Esthétique',
    'feature.3.desc': 'Des designs esthétiques sur mesure pour vos traits uniques.',
    'feature.4.title': 'Forfaits Tout Compris',
    'feature.4.desc': 'Traitement, hébergement et transferts inclus.',

    // Home Treatments Section
    'home.treatments.title': 'Nos Traitements Phares',
    'home.treatments.subtitle': 'Découvrez nos procédures les plus recherchées, approuvées par des patients de plus de 50 pays',
    
    // Testimonials
    'testimonials.title': 'Ce Que Disent Nos Patients',
    'testimonials.1.text': 'Expérience incroyable! Le personnel était professionnel et les résultats ont dépassé mes attentes.',
    'testimonials.1.name': 'Jean Dupont',
    'testimonials.1.treatment': 'Implants Dentaires',
    'testimonials.2.text': 'Meilleure décision que j\'ai jamais prise. Les médecins étaient attentionnés et la clinique impeccable.',
    'testimonials.2.name': 'Sophie Martin',
    'testimonials.2.treatment': 'Facettes',
    'testimonials.3.text': 'Résultats de greffe capillaire incroyables! Aspect naturel et processus indolore.',
    'testimonials.3.name': 'Michel Bernard',
    'testimonials.3.treatment': 'Greffe FUE',
    'testimonials.subtitle': 'Des milliers de patients nous font confiance chaque année',

    // Home Results
    'home.results.title': 'Résultats Réels, Histoires Réelles',
    'home.results.subtitle': 'Découvrez la transformation de nos patients. Nous sommes fiers de fournir des résultats naturels et de haute qualité qui changent des vies.',
    'home.results.cta': 'Voir Toutes les Histoires de Transformation',
    'home.results.1.label': 'Conception de Sourire Numérique',
    'home.results.1.title': 'Un Sourire qui Change la Vie',
    'home.results.1.text': 'J\'ai toujours été complexée par mon sourire. L\'équipe de Gravity Clinic a utilisé la dernière technologie de conception numérique pour me montrer mon futur sourire avant même de commencer. Le résultat est meilleur que ce que j\'aurais pu imaginer.',
    'home.results.1.category': 'Esthétique Dentaire',
    'home.results.1.patient': 'Patiente: Sarah M.',
    'home.results.2.label': 'Restauration Capillaire Soft-FUE',
    'home.results.2.title': 'Ligne de Cheveux Naturelle Restaurée',
    'home.results.2.text': 'Choisir Gravity Clinic pour ma greffe de cheveux a été la meilleure décision. La procédure FUE a été sans douleur et la récupération a été remarquablement rapide. Six mois plus tard, mes cheveux ont l\'air complètement naturels.',
    'home.results.2.category': 'Greffe de Cheveux',
    'home.results.2.patient': 'Patient: James L.',
    
    // Home CTA
    'home.cta.title': 'Prêt à Transformer Votre Vie ?',
    'home.cta.subtitle': 'Prenez votre consultation gratuite aujourd\'hui et découvrez la différence',

    // Dental Treatments
    'dental.title': 'Traitements Dentaires',
    'dental.subtitle': 'Soins dentaires complets avec technologie de pointe',
    'dental.implants': 'Implants Dentaires',
    'dental.implants.desc': 'Solution permanente de remplacement dentaire avec implants en titane.',
    'dental.implants.price': 'Contactez-nous',
    'dental.whitening': 'Blanchiment des Dents',
    'dental.whitening.desc': 'Blanchiment professionnel pour un sourire éclatant.',
    'dental.whitening.price': 'Contactez-nous',
    'dental.veneers': 'Facettes en Porcelaine / Emax',
    'dental.veneers.desc': 'Transformez votre sourire avec des facettes sur mesure (Hollywood Smile).',
    'dental.veneers.price': 'Contactez-nous',
    'dental.braces': 'Couronnes en Zircone',
    'dental.braces.desc': 'Haute durabilité et couronnes à l\'aspect naturel pour la restauration.',
    'dental.braces.price': 'Contactez-nous',
    'dental.crowns': 'Lumineers',
    'dental.crowns.desc': 'Facettes ultra-fines pour une amélioration sans soudure du sourire.',
    'dental.crowns.price': 'Contactez-nous',
    'dental.rootcanal': 'Traitement de Canal',
    'dental.rootcanal.desc': 'Thérapie de canal radiculaire sans douleur.',
    'dental.rootcanal.price': 'Contactez-nous',

    // Dental Treatment Keys (Used in Dental.tsx)
    'dental.treatment.implants.title': 'Implants Dentaires',
    'dental.treatment.implants.desc': 'Solution permanente de remplacement dentaire avec implants en titane et couronnes personnalisées.',
    'dental.treatment.whitening.title': 'Blanchiment des Dents',
    'dental.treatment.whitening.desc': 'Blanchiment professionnel pour un sourire éclatant utilisant une technologie laser avancée.',
    'dental.treatment.veneers.title': 'Facettes en Porcelaine / Emax',
    'dental.treatment.veneers.desc': 'Transformez votre sourire avec des facettes sur mesure et la conception Hollywood Smile.',
    'dental.treatment.braces.title': 'Couronnes en Zircone',
    'dental.treatment.braces.desc': 'Haute durabilité et couronnes à l\'aspect naturel pour la restauration esthétique.',
    'dental.treatment.crowns.title': 'Lumineers',
    'dental.treatment.crowns.desc': 'Facettes ultra-fines pour une amélioration sans couture du sourire.',
    'dental.treatment.rootcanal.title': 'Traitement de Canal',
    'dental.treatment.rootcanal.desc': 'Thérapie de canal radiculaire sans douleur pour sauver votre dent naturelle.',

    // Dental Features
    'dental.f.implants.1': 'Implants en titane',
    'dental.f.implants.2': 'Garantie à vie',
    'dental.f.implants.3': 'Procédure sans douleur',
    'dental.f.implants.4': 'Apparence naturelle',
    'dental.f.whitening.1': 'Qualité professionnelle',
    'dental.f.whitening.2': 'Résultats immédiats',
    'dental.f.whitening.3': 'Sûr pour l\'émail',
    'dental.f.whitening.4': '8-10 nuances plus blanches',
    'dental.f.veneers.1': 'Porcelaine sur mesure',
    'dental.f.veneers.2': 'Résistant aux taches',
    'dental.f.veneers.3': 'Durée de vie 15-20 ans',
    'dental.f.veneers.4': 'Alignement parfait',
    'dental.f.braces.1': 'Options métal ou céramique',
    'dental.f.braces.2': 'Ajustements réguliers',
    'dental.f.braces.3': 'Traitement 12-24 mois',
    'dental.f.braces.4': 'Plans de paiement disponibles',
    'dental.f.crowns.1': 'Zircone ou porcelaine',
    'dental.f.crowns.2': 'Correspondance parfaite des couleurs',
    'dental.f.crowns.3': 'Matériaux durables',
    'dental.f.crowns.4': 'Procédure en deux visites',
    'dental.f.rootcanal.1': 'Sauver la dent naturelle',
    'dental.f.rootcanal.2': 'Microscopes avancés',
    'dental.f.rootcanal.3': 'Traitement sans douleur',
    'dental.f.rootcanal.4': 'Taux de réussite élevé',
    
    // Hair Treatments
    'hair.title': 'Restauration Capillaire',
    'hair.subtitle': 'Techniques avancées de greffe de cheveux pour des résultats naturels',
    'hair.fue': 'Greffe de Cheveux pour Hommes',
    'hair.fue.desc': 'Déplacement des cheveux sains vers les zones chauves sous anesthésie locale.',
    'hair.fue.price': 'Contactez-nous',
    'hair.dhi': 'Greffe DHI',
    'hair.dhi.desc': 'Implantation directe pour un placement précis et une densité maximale.',
    'hair.dhi.price': 'Contactez-nous',
    'hair.sapphire': 'FUE Saphir',
    'hair.sapphire.desc': 'FUE avancée avec lames de saphir pour une guérison plus rapide.',
    'hair.sapphire.price': 'Contactez-nous',
    'hair.prp': 'Thérapie PRP',
    'hair.prp.desc': 'Traitement au plasma riche en plaquettes pour stimuler la croissance.',
    'hair.prp.price': 'Contactez-nous',
    'hair.beard': 'Greffe de Barbe',
    'hair.beard.desc': 'Obtenez une barbe plus fournie et mieux définie.',
    'hair.beard.price': 'Contactez-nous',
    'hair.eyebrow': 'Greffe de Sourcils',
    'hair.eyebrow.desc': 'Restauration naturelle des sourcils.',
    'hair.eyebrow.price': 'Contactez-nous',

    // Hair Treatment Keys (Used in Hair.tsx)
    'hair.treatment.fue.title': 'Greffe de Cheveux FUE',
    'hair.treatment.fue.desc': 'Extraction d\'unités folliculaires pour des résultats naturels et une densité maximale.',
    'hair.treatment.dhi.title': 'Greffe de Cheveux DHI',
    'hair.treatment.dhi.desc': 'Implantation directe pour un placement précis et une récupération plus rapide.',
    'hair.treatment.sapphire.title': 'FUE Saphir',
    'hair.treatment.sapphire.desc': 'FUE avancée avec lames de saphir pour un traumatisme minimal et une guérison rapide.',
    'hair.treatment.prp.title': 'Thérapie PRP',
    'hair.treatment.prp.desc': 'Traitement au plasma riche en plaquettes pour stimuler les follicules pileux et la croissance.',
    'hair.treatment.beard.title': 'Greffe de Barbe',
    'hair.treatment.beard.desc': 'Obtenez une barbe plus fournie et mieux définie avec une récolte de précision.',
    'hair.treatment.eyebrow.title': 'Greffe de Sourcils',
    'hair.treatment.eyebrow.desc': 'Restauration naturelle des sourcils utilisant le micro-greffage avancé.',

    // Hair Features
    'hair.f.fue.1': '3000-5000 greffons',
    'hair.f.fue.2': 'Pas de cicatrices visibles',
    'hair.f.fue.3': 'Design naturel de la ligne frontale',
    'hair.f.fue.4': 'Minimalement invasif',
    'hair.f.dhi.1': 'Stylo implanteur Choi',
    'hair.f.dhi.2': 'Densité maximale',
    'hair.f.dhi.3': 'Manipulation minimale',
    'hair.f.dhi.4': 'Pas d\'incisions nécessaires',
    'hair.f.sapphire.1': 'Technologie de lame saphir',
    'hair.f.sapphire.2': 'Guérison plus rapide',
    'hair.f.sapphire.3': 'Moins de traumatismes',
    'hair.f.sapphire.4': 'Greffons de haute précision',
    'hair.f.prp.1': 'Facteurs de croissance naturels',
    'hair.f.prp.2': 'Non chirurgical',
    'hair.f.prp.3': '3-6 sessions recommandées',
    'hair.f.prp.4': 'Cheveux plus épais',
    'hair.f.beard.1': '1500-3000 greffons',
    'hair.f.beard.2': 'Forme personnalisée',
    'hair.f.beard.3': 'Direction naturelle',
    'hair.f.beard.4': 'Résultats permanents',
    'hair.f.eyebrow.1': '300-800 greffons',
    'hair.f.eyebrow.2': 'Arc naturel',
    'hair.f.eyebrow.3': 'Placement précis',
    'hair.f.eyebrow.4': 'Amélioration subtile',

    // Hair Why
    'hair.why.1.title': 'Chirurgiens Experts',
    'hair.why.1.desc': '15+ ans d\'expérience en restauration capillaire',
    'hair.why.2.title': 'Techniques Avancées',
    'hair.why.2.desc': 'Dernières méthodes FUE, DHI et Saphir',
    'hair.why.3.title': 'Résultats Naturels',
    'hair.why.3.desc': 'Taux de réussite de 95 %+ avec des résultats permanents',
    
    // Doctors
    'doctors.title': 'Rencontrez Notre Équipe',
    'doctors.subtitle': 'Spécialistes internationaux dévoués à vos soins',
    
    // Booking
    'booking.title': 'Réservez Votre Consultation',
    'booking.step1': 'Informations Personnelles',
    'booking.step2': 'Sélection du Traitement',
    'booking.step3': 'Date Préférée',
    'booking.step4': 'Confirmation',
    'booking.firstName': 'Prénom',
    'booking.lastName': 'Nom',
    'booking.email': 'Email',
    'booking.phone': 'Téléphone',
    'booking.country': 'Pays',
    'booking.treatment': 'Sélectionner le Traitement',
    'booking.date': 'Date Préférée',
    'booking.message': 'Informations Supplémentaires',
    'booking.next': 'Suivant',
    'booking.previous': 'Précédent',
    'booking.submit': 'Envoyer la Réservation',
    
    // Contact
    'contact.title': 'Contactez-Nous',
    'contact.subtitle': 'Nous sommes là pour répondre à vos questions',
    'contact.form.title': 'Envoyez-nous un message',
    'contact.name': 'Votre Nom',
    'contact.subject': 'Sujet',
    'contact.send': 'Envoyer',
    'contact.locations': 'Nos Emplacements',
    'contact.faq': 'Questions Fréquentes',
    'contact.about': 'Gravity Clinic est une destination de choix à Istanbul spécialisée dans les traitements dentaires et les greffes de cheveux. Notre équipe d\'experts s\'engage à fournir des soins personnalisés en utilisant une technologie de pointe pour des résultats qui changent la vie.',
    
    // Common
    'common.learnMore': 'En Savoir Plus',
    'common.bookNow': 'Réserver',
    'common.readMore': 'Lire Plus',
    'common.viewAll': 'Voir Tout',
    'common.features': 'Caractéristiques',
    'common.pricing': 'Tarifs',
    'common.gallery': 'Galerie',
    'common.years': 'Années d\'Expérience',
    'common.patients': 'Patients',
    'common.viewProfile': 'Voir le Profil',
    'common.education': 'Éducation et Expertise',
    'common.languages': 'Langues',
    'common.successRate': 'Taux de Réussite',
    'common.viewDetails': 'Voir les Détails',
    'common.whatsappSupport': 'Support sur WhatsApp',
    'common.patientSatisfaction': 'Satisfaction des Patients',
    'common.successfulResults': 'Résultats Réussis',
    'common.duration': 'Durée',
    'common.procedure': 'Procédure',
    'common.appointments': 'Rendez-vous',
    'common.oneDay': 'Un Jour',
    'common.hours': 'Heures',

    // Hero Badge
    'hero.clinic.badge': 'Clinique Internationale Accréditée JCI',

    // Doctors
    'doctors.sarah.specialty': 'Chirurgien Dentaire en Chef',
    'doctors.sarah.bio': 'Chirurgien dentaire certifié spécialisé dans les implants et la dentisterie esthétique. Diplômée de la Harvard School of Dental Medicine.',
    'doctors.michael.specialty': 'Spécialiste en Orthodontie',
    'doctors.michael.bio': 'Expert en orthodontie moderne avec un accent sur les aligneurs invisibles et les méthodes de traitement accélérées.',
    'doctors.ahmed.specialty': 'Chirurgien de Greffe Capillaire',
    'doctors.ahmed.bio': 'Pionnier des techniques FUE et DHI avec des milliers de greffes de cheveux réussies. Conférencier et formateur international.',
    'doctors.emily.specialty': 'Dentiste Esthétique',
    'doctors.emily.bio': 'Passionnée par la création de beaux sourires grâce à des procédures cosmétiques avancées et des techniques peu invasives.',
    'doctors.mehmet.specialty': 'Expert en Restauration Capillaire',
    'doctors.mehmet.bio': 'Spécialisé dans la conception de la ligne frontale naturelle et les greffes à haute densité. Membre de l\'ISHRS.',
    'doctors.lisa.specialty': 'Endodontiste',
    'doctors.lisa.bio': 'Experte en thérapie de canal et en gestion de la douleur utilisant les dernières techniques microscopiques.',

    // Booking
    'booking.hero.subtitle': 'Votre voyage vers un meilleur vous commence par une seule étape.',
    'booking.step1.desc': 'Veuillez partager vos coordonnées pour la coordination VIP.',
    'booking.step2.desc': 'Sélectionnez la spécialité qui vous intéresse.',
    'booking.step3.desc': 'Choisissez votre fenêtre d\'arrivée préférée.',
    'booking.step4.desc': 'Vérifiez vos informations avant de finaliser.',
    'booking.success.title': 'Réservation Reçue',
    'booking.success.desc': 'Merci, {name}. Notre équipe de soins aux patients vous contactera dans les 2 à 4 heures ouvrables.',

    // Contact
    'contact.info.title': 'Contactez-nous',
    'contact.info.desc': 'Vous avez des questions ? Notre équipe amicale est là pour vous aider.',
    'contact.faq.subtitle': 'Questions courantes sur nos voyages médicaux de luxe',
    'contact.workingHours': 'Heures de Travail',
    'contact.monSat': 'Lundi - Samedi',
    'contact.sunday': 'Dimanche',
    'contact.closed': 'Fermé',

    // Articles
    'articles.hero.badge': 'Médecine Fondée sur les Preuves',
    'articles.hero.subtitle': 'Aperçus d\'experts et guides cliniques organisés par les plus grands spécialistes du monde.',
    'articles.filter.all': 'Volume : Tout',
    'articles.filter.dental': 'Spécialité : Dentaire',
    'articles.filter.hair': 'Spécialité : Cheveux',
    'articles.newsletter.badge': 'Accès Privilégié',
    'articles.newsletter.title': 'Recevez la Précision dans Votre Boîte de Réception',
    'articles.newsletter.subtitle': 'Rejoignez plus de 5 000 patients qui reçoivent des perles cliniques mensuelles et des percées de nos spécialistes.',
    'articles.newsletter.cta': 'Rejoindre la Liste Exclusive',
    
    // Common
    'common.restoration': 'Restauration',
    'footer.expertise': 'Notre Expertise',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'footer.desc': 'Établir la norme mondiale en matière de tourisme médical de luxe. Précision, art et innovation dans chaque procédure.',
    'footer.whatsapp': 'WhatsApp/Téléphone',
    'footer.istanbul': 'Bureau d\'Istanbul',
    'footer.address': 'Nisantasi, Tesvikiye No: 42',
    'footer.hours': 'Heures de Clinique',
    'footer.monSat': 'Lun - Sam',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.copyright': '© 2026 Gravity Clinic Global. Toutes les procédures sont effectuées par des professionnels certifiés.',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.dental': 'Стоматология',
    'nav.dental.implants': 'Имплантация Зубов',
    'nav.dental.hollywood': 'Голливудская Улыбка',
    'nav.hair': 'Пересадка Волос',
    'nav.hair.male': 'Пересадка Волос у Мужчин',
    'nav.hair.female': 'Пересадка Волос у Женщин',
    'nav.hair.beard': 'Пересадка Бороды и Усов',
    'nav.hair.eyebrow': 'Пересадка Бровей',
    'nav.about': 'О Нас',
    'nav.about.appointment': 'Запись на Прием',
    'nav.about.blog': 'Блог',
    'nav.about.contact': 'Связаться с Нами',
    'nav.articles': 'Статьи',
    'nav.doctors': 'Наши Врачи',
    'nav.booking': 'Записаться',
    'nav.contact': 'Контакты',
    
    // Hero
    'hero.title': 'Преобразите Свою Жизнь с Премиальной Медициной',
    'hero.subtitle': 'Потому Что у Зубов Тоже Есть Чувства. Наслаждайтесь Специализированным Уходом Благодаря Точности, Искусству и Опыту.',
    'hero.cta': 'Бесплатная Консультация',
    'hero.subheader': 'Медицинский туризм премиум-класса',
    'hero.watchTour': 'Смотреть тур по клинике',

    // Stats
    'stats.patients': 'Счастливых пациентов',
    'stats.years': 'Лет совершенства',
    'stats.success': 'Успешность',
    'stats.countries': 'Обслуживаемых стран',
    
    // Features
    'feature.title': 'Почему Мы',
    'feature.subtitle': 'Уход мирового уровня, доступное превосходство — все в одном месте.',
    'feature.1.title': 'Специалисты-Эксперты',
    'feature.1.desc': 'Сертифицированные врачи с международным опытом.',
    'feature.2.title': 'Современное Оборудование',
    'feature.2.desc': 'Передовые технологии и оборудование.',
    'feature.3.title': 'Точность и Искусство',
    'feature.3.desc': 'Индивидуальный эстетический дизайн.',
    'feature.4.title': 'Полный Пакет',
    'feature.4.desc': 'Лечение, проживание и трансфер включены.',

    // Home Treatments Section
    'home.treatments.title': 'Наши Фирменные Процедуры',
    'home.treatments.subtitle': 'Откройте для себя наши самые востребованные процедуры, которым доверяют пациенты из 50+ стран',
    
    // Testimonials
    'testimonials.title': 'Отзывы Пациентов',
    'testimonials.1.text': 'Потрясающий опыт! Профессиональный персонал и результаты превзошли ожидания.',
    'testimonials.1.name': 'Иван Петров',
    'testimonials.1.treatment': 'Зубные Имплантаты',
    'testimonials.2.text': 'Лучшее решение в моей жизни. Заботливые врачи и безупречная клиника.',
    'testimonials.2.name': 'Ольга Соколова',
    'testimonials.2.treatment': 'Виниры',
    'testimonials.3.text': 'Невероятные результаты пересадки волос! Естественный вид и безболезненный процесс.',
    'testimonials.3.name': 'Михаил Смирнов',
    'testimonials.3.treatment': 'FUE Пересадка',
    'testimonials.subtitle': 'Тысячи пациентов доверяют нам каждый год',

    // Home Results
    'home.results.title': 'Реальные Результаты, Реальные Истории',
    'home.results.subtitle': 'Узнайте о преображении наших пациентов. Мы гордимся тем, что обеспечиваем естественные и высококачественные результаты, которые меняют жизнь.',
    'home.results.cta': 'Посмотреть все истории преображения',
    'home.results.1.label': 'Digital Smile Design',
    'home.results.1.title': 'Улыбка, меняющая жизнь',
    'home.results.1.text': 'Я всегда стеснялась своей улыбки. Команда Gravity Clinic использовала новейшие технологии цифрового дизайна, чтобы показать мне мою будущую улыбку еще до начала работы. Результат превзошел все мои ожидания.',
    'home.results.1.category': 'Эстетическая стоматология',
    'home.results.1.patient': 'Пациент: Сара М.',
    'home.results.2.label': 'Восстановление волос Soft-FUE',
    'home.results.2.title': 'Естественная линия роста волос восстановлена',
    'home.results.2.text': 'Выбор Gravity Clinic для пересадки волос был лучшим решением. Процедура FUE была безболезненной, а восстановление — удивительно быстрым. Через шесть месяцев мои волосы выглядят совершенно естественно.',
    'home.results.2.category': 'Пересадка волос',
    'home.results.2.patient': 'Пациент: Джеймс Л.',
    
    // Home CTA
    'home.cta.title': 'Готовы Преобразить Свою Жизнь?',
    'home.cta.subtitle': 'Запишитесь на бесплатную консультацию сегодня и почувствуйте разницу',

    // Dental Treatments
    'dental.title': 'Стоматологические Услуги',
    'dental.subtitle': 'Комплексная стоматологическая помощь с передовыми технологиями',
    'dental.implants': 'Зубные Имплантаты',
    'dental.implants.desc': 'Постоянное решение замены зубов с титановыми имплантатами.',
    'dental.implants.price': 'Свяжитесь для уточнения цен',
    'dental.whitening': 'Отбеливание Зубов',
    'dental.whitening.desc': 'Профессиональное отбеливание для яркой улыбки.',
    'dental.whitening.price': 'Свяжитесь для уточнения цен',
    'dental.veneers': 'Фарфоровые / Емакс Виниры',
    'dental.veneers.desc': 'Преобразите улыбку с индивидуальными винирами (Hollywood Smile).',
    'dental.veneers.price': 'Свяжитесь для уточнения цен',
    'dental.braces': 'Циркониевые Коронки',
    'dental.braces.desc': 'Высокопрочные коронки для эстетического восстановления.',
    'dental.braces.price': 'Свяжитесь для уточнения цен',
    'dental.crowns': 'Люминиры',
    'dental.crowns.desc': 'Ультратонкие виниры для безупречной улыбки.',
    'dental.crowns.price': 'Свяжитесь для уточнения цен',
    'dental.rootcanal': 'Лечение Каналов',
    'dental.rootcanal.desc': 'Безболезненное эндодонтическое лечение.',
    'dental.rootcanal.price': 'Свяжитесь для уточнения цен',

    // Dental Treatment Keys (Used in Dental.tsx)
    'dental.treatment.implants.title': 'Зубные имплантаты',
    'dental.treatment.implants.desc': 'Постоянное решение по замене зубов с помощью титановых имплантатов и индивидуальных коронок.',
    'dental.treatment.whitening.title': 'Отбеливание зубов',
    'dental.treatment.whitening.desc': 'Профессиональное отбеливание для яркой, уверенной улыбки с использованием передовых лазерных технологий.',
    'dental.treatment.veneers.title': 'Фарфоровые / Emax виниры',
    'dental.treatment.veneers.desc': 'Преобразите свою улыбку с помощью виниров, изготовленных на заказ, и дизайна Hollywood Smile.',
    'dental.treatment.braces.title': 'Циркониевые коронки',
    'dental.treatment.braces.desc': 'Высокая прочность и естественный вид коронок для эстетического восстановления.',
    'dental.treatment.crowns.title': 'Люминиры',
    'dental.treatment.crowns.desc': 'Ультратонкие виниры для безупречного улучшения улыбки.',
    'dental.treatment.rootcanal.title': 'Лечение корневых каналов',
    'dental.treatment.rootcanal.desc': 'Безболезненная терапия корневых каналов для сохранения вашего естественного зуба.',

    // Dental Features
    'dental.f.implants.1': 'Титановые имплантаты',
    'dental.f.implants.2': 'Пожизненная гарантия',
    'dental.f.implants.3': 'Безболезненная процедура',
    'dental.f.implants.4': 'Естественный вид',
    'dental.f.whitening.1': 'Профессиональный уровень',
    'dental.f.whitening.2': 'Мгновенный результат',
    'dental.f.whitening.3': 'Безопасно для эмали',
    'dental.f.whitening.4': 'На 8-10 тонов светлее',
    'dental.f.veneers.1': 'Индивидуальный фарфор',
    'dental.f.veneers.2': 'Устойчивость к пятнам',
    'dental.f.veneers.3': 'Срок службы 15-20 лет',
    'dental.f.veneers.4': 'Идеальное выравнивание',
    'dental.f.braces.1': 'Металлические или керамические варианты',
    'dental.f.braces.2': 'Регулярные регулировки',
    'dental.f.braces.3': 'Лечение 12-24 месяца',
    'dental.f.braces.4': 'Доступны планы оплаты',
    'dental.f.crowns.1': 'Диоксид циркония или фарфор',
    'dental.f.crowns.2': 'Идеальное попадание в цвет',
    'dental.f.crowns.3': 'Долговечные материалы',
    'dental.f.crowns.4': 'Процедура в два посещения',
    'dental.f.rootcanal.1': 'Сохранение естественного зуба',
    'dental.f.rootcanal.2': 'Современные микроскопы',
    'dental.f.rootcanal.3': 'Безболезненное лечение',
    'dental.f.rootcanal.4': 'Высокая вероятность успеха',
    
    // Hair Treatments
    'hair.title': 'Восстановление Волос',
    'hair.subtitle': 'Передовые методы трансплантации для естественных результатов',
    'hair.fue': 'Пересадка Волос для Мужчин',
    'hair.fue.desc': 'Перемещение здоровых волос в облысевшие участки под местной анестезией.',
    'hair.fue.price': 'Свяжитесь для уточнения цен',
    'hair.dhi': 'DHI Пересадка',
    'hair.dhi.desc': 'Прямая имплантация для точного размещения.',
    'hair.dhi.price': 'Свяжитесь для уточнения цен',
    'hair.sapphire': 'Сапфировая FUE',
    'hair.sapphire.desc': 'Продвинутая FUE с сапфировыми лезвиями.',
    'hair.sapphire.price': 'Свяжитесь для уточнения цен',
    'hair.prp': 'PRP Терапия',
    'hair.prp.desc': 'Лечение богатой тромбоцитами плазмой.',
    'hair.prp.price': 'Свяжитесь для уточнения цен',
    'hair.beard': 'Пересадка Бороды',
    'hair.beard.desc': 'Получите более густую и четкую бороду.',
    'hair.beard.price': 'Свяжитесь для уточнения цен',
    'hair.eyebrow': 'Пересадка Бровей',
    'hair.eyebrow.desc': 'Естественное восстановление бровей.',
    'hair.eyebrow.price': 'Свяжитесь для уточнения цен',

    // Hair Treatment Keys (Used in Hair.tsx)
    'hair.treatment.fue.title': 'Пересадка волос FUE',
    'hair.treatment.fue.desc': 'Экстракция фолликулярных объединений для получения естественных результатов и максимальной густоты волос.',
    'hair.treatment.dhi.title': 'Пересадка волос DHI',
    'hair.treatment.dhi.desc': 'Прямая имплантация волос для точного размещения и более быстрого восстановления.',
    'hair.treatment.sapphire.title': 'Сапфировая FUE',
    'hair.treatment.sapphire.desc': 'Усовершенствованная FUE с использованием сапфировых лезвий для минимальной травматизации и быстрого заживления.',
    'hair.treatment.prp.title': 'PRP-терапия',
    'hair.treatment.prp.desc': 'Лечение плазмой, богатой тромбоцитами, для стимулирования волосяных фолликуров и роста.',
    'hair.treatment.beard.title': 'Пересадка бороды',
    'hair.treatment.beard.desc': 'Добейтесь более густой и четкой бороды с помощью высокоточного сбора трансплантатов.',
    'hair.treatment.eyebrow.title': 'Пересадка бровей',
    'hair.treatment.eyebrow.desc': 'Естественное восстановление бровей с использованием современного микрографтинга.',

    // Hair Features
    'hair.f.fue.1': '3000-5000 графтов',
    'hair.f.fue.2': 'Отсутствие видимых шрамов',
    'hair.f.fue.3': 'Натуральный дизайн линии роста волос',
    'hair.f.fue.4': 'Минимально инвазивный',
    'hair.f.dhi.1': 'Ручка-имплантер Choi',
    'hair.f.dhi.2': 'Максимальная густота',
    'hair.f.dhi.3': 'Минимальное воздействие',
    'hair.f.dhi.4': 'Разрезы не требуются',
    'hair.f.sapphire.1': 'Технология сапфирового лезвия',
    'hair.f.sapphire.2': 'Более быстрое заживление',
    'hair.f.sapphire.3': 'Меньше травматизма',
    'hair.f.sapphire.4': 'Высокоточные графты',
    'hair.f.prp.1': 'Натуральные факторы роста',
    'hair.f.prp.2': 'Нехирургический метод',
    'hair.f.prp.3': 'Рекомендуется 3-6 сеансов',
    'hair.f.prp.4': 'Более густые волосы',
    'hair.f.beard.1': '1500-3000 графтов',
    'hair.f.beard.2': 'Индивидуальная форма',
    'hair.f.beard.3': 'Естественное направление роста',
    'hair.f.beard.4': 'Постоянный результат',
    'hair.f.eyebrow.1': '300-800 графтов',
    'hair.f.eyebrow.2': 'Естественная арка',
    'hair.f.eyebrow.3': 'Точное размещение',
    'hair.f.eyebrow.4': 'Тонкое улучшение',

    // Hair Why
    'hair.why.1.title': 'Опытные хирурги',
    'hair.why.1.desc': '15+ лет опыта в восстановлении волос',
    'hair.why.2.title': 'Передовые методы',
    'hair.why.2.desc': 'Новейшие методы FUE, DHI и Sapphire',
    'hair.why.3.title': 'Естественные результаты',
    'hair.why.3.desc': '95%+ успеха с пожизненным результатом',
    
    // Doctors
    'doctors.title': 'Наша Команда Экспертов',
    'doctors.subtitle': 'Международные специалисты, преданные вашему здоровью',
    
    // Booking
    'booking.title': 'Запись на Консультацию',
    'booking.step1': 'Личная Информация',
    'booking.step2': 'Выбор Процедуры',
    'booking.step3': 'Предпочтительная Дата',
    'booking.step4': 'Подтверждение',
    'booking.firstName': 'Имя',
    'booking.lastName': 'Фамилия',
    'booking.email': 'Email',
    'booking.phone': 'Телефон',
    'booking.country': 'Страна',
    'booking.treatment': 'Выберите Процедуру',
    'booking.date': 'Предпочтительная Дата',
    'booking.message': 'Дополнительная Информация',
    'booking.next': 'Далее',
    'booking.previous': 'Назад',
    'booking.submit': 'Отправить Заявку',
    
    // Contact
    'contact.title': 'Свяжитесь с Нами',
    'contact.subtitle': 'Мы готовы ответить на ваши вопросы',
    'contact.form.title': 'Отправьте нам сообщение',
    'contact.name': 'Ваше Имя',
    'contact.subject': 'Тема',
    'contact.send': 'Отправить',
    'contact.locations': 'Наши Офисы',
    'contact.faq': 'Часто Задаваемые Вопросы',
    'contact.about': 'Gravity Clinic - это ведущее медицинское учреждение в Стамбуле, специализирующееся на передовых стоматологических процедурах и пересадке волос.',
    
    // Common
    'common.learnMore': 'Подробнее',
    'common.bookNow': 'Записаться',
    'common.readMore': 'Читать Далее',
    'common.viewAll': 'Показать Все',
    'common.features': 'Особенности',
    'common.pricing': 'Цены',
    'common.gallery': 'Галерея',
    'common.years': 'Лет Опыта',
    'common.patients': 'Пациентов',
    'common.viewProfile': 'Профиль',
    'common.education': 'Образование и Опыт',
    'common.languages': 'Языки',
    'common.successRate': 'Успешность',
    'common.viewDetails': 'Подробнее',
    'common.whatsappSupport': 'Поддержка в WhatsApp',
    'common.patientSatisfaction': 'Удовлетворенность пациентов',
    'common.successfulResults': 'Успешные результаты',
    'common.duration': 'Продолжительность',
    'common.procedure': 'Процедура',
    'common.appointments': 'Приемы',
    'common.oneDay': 'Один день',
    'common.hours': 'Часы',

    // Hero Badge
    'hero.clinic.badge': 'Международная клиника, аккредитованная JCI',

    // Doctors
    'doctors.sarah.specialty': 'Главный стоматолог-хирург',
    'doctors.sarah.bio': 'Сертифицированный стоматолог-хирург, специализирующийся на имплантации и эстетической стоматологии. Выпускница Гарвардской школы стоматологии.',
    'doctors.michael.specialty': 'Специалист-ортодонт',
    'doctors.michael.bio': 'Эксперт в современной ортодонтии с акцентом на невидимые элайнеры и ускоренные методы лечения.',
    'doctors.ahmed.specialty': 'Хирург по пересадке волос',
    'doctors.ahmed.bio': 'Пионер технологий FUE и DHI с тысячами успешных пересадок волос. Международный спикер и тренер.',
    'doctors.emily.specialty': 'Эстетический стоматолог',
    'doctors.emily.bio': 'Увлечена созданием красивых улыбок с помощью передовых косметических процедур и малоинвазивных методов.',
    'doctors.mehmet.specialty': 'Эксперт по восстановлению волос',
    'doctors.mehmet.bio': 'Специализируется на дизайне естественной линии роста волос и трансплантации высокой плотности. Член ISHRS.',
    'doctors.lisa.specialty': 'Эндодонтист',
    'doctors.lisa.bio': 'Эксперт в лечении корневых каналов и управлении болью с использованием новейших микроскопических технологий.',

    // Booking
    'booking.hero.subtitle': 'Ваш путь к лучшему себе начинается с одного шага.',
    'booking.step1.desc': 'Пожалуйста, поделитесь своими контактными данными для VIP-координации.',
    'booking.step2.desc': 'Выберите специализацию, которая вас интересует.',
    'booking.step3.desc': 'Выберите предпочтительное время прибытия.',
    'booking.step4.desc': 'Проверьте свою информацию перед завершением.',
    'booking.success.title': 'Заявка Получена',
    'booking.success.desc': 'Спасибо, {name}. Наша команда по уходу за пациентами свяжется с вами в течение 2-4 рабочих часов.',

    // Contact
    'contact.info.title': 'Свяжитесь с нами',
    'contact.info.desc': 'Есть вопросы? Наша дружная команда всегда готова помочь.',
    'contact.faq.subtitle': 'Частые вопросы о наших медицинских турах класса люкс',
    'contact.workingHours': 'Рабочие Часы',
    'contact.monSat': 'Понедельник - Суббота',
    'contact.sunday': 'Воскресенье',
    'contact.closed': 'Закрыто',

    // Articles
    'articles.hero.badge': 'Доказательная медицина',
    'articles.hero.subtitle': 'Экспертные заключения и клинические руководства от ведущих мировых специалистов.',
    'articles.filter.all': 'Все статьи',
    'articles.filter.dental': 'Стоматология',
    'articles.filter.hair': 'Волосы',
    'articles.newsletter.badge': 'Инсайдерский доступ',
    'articles.newsletter.title': 'Получайте новости в свой почтовый ящик',
    'articles.newsletter.subtitle': 'Присоединяйтесь к 5000+ пациентам, которые получают ежемесячные новости и информацию о прорывных методах лечения.',
    'articles.newsletter.cta': 'Присоединиться к списку',
    
    // Common
    'common.restoration': 'Восстановление',
    'footer.expertise': 'Наш Опыт',
    'footer.navigation': 'Навигация',
    'footer.contact': 'Контакт',
    'footer.desc': 'Установление мирового стандарта в роскошном медицинском туризме. Точность, искусство и инновации в каждой процедуре.',
    'footer.whatsapp': 'WhatsApp/Телефон',
    'footer.istanbul': 'Офис в Стамбуле',
    'footer.address': 'Нишанташи, Тешвикие № 42',
    'footer.hours': 'Часы Работы',
    'footer.monSat': 'Пн - Сб',
    'footer.privacy': 'Политика Конфиденциальности',
    'footer.terms': 'Условия Обслуживания',
    'footer.copyright': '© 2026 Gravity Clinic Global. Все процедуры проводятся сертифицированными врачами.',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.dental': 'الأسنان',
    'nav.dental.implants': 'زراعة الأسنان',
    'nav.dental.hollywood': 'ابتسامة هوليوود',
    'nav.hair': 'زراعة الشعر',
    'nav.hair.male': 'زراعة الشعر للرجال',
    'nav.hair.female': 'زراعة الشعر للنساء',
    'nav.hair.beard': 'زراعة اللحية والشارب',
    'nav.hair.eyebrow': 'زراعة الحواجب',
    'nav.about': 'من نحن',
    'nav.about.appointment': 'موعد',
    'nav.about.blog': 'المدونة',
    'nav.about.contact': 'اتصل بنا',
    'nav.articles': 'المقالات',
    'nav.doctors': 'أطباؤنا',
    'nav.booking': 'احجز الآن',
    'nav.contact': 'اتصل بنا',
    
    // Hero
    'hero.title': 'حوّل حياتك مع رعاية طبية متميزة',
    'hero.subtitle': 'لأن الأسنان لها إحساس أيضًا. تمتع برعاية متخصصة من خلال الدقة والفن والخبرة.',
    'hero.cta': 'استشارة مجانية',
    'hero.subheader': 'السياحة العلاجية المتميزة',
    'hero.watchTour': 'مشاهدة جولة في العيادة',

    // Stats
    'stats.patients': 'مريض سعيد',
    'stats.years': 'سنوات من التميز',
    'stats.success': 'نسبة النجاح',
    'stats.countries': 'دولة نخدمها',
    
    // Features
    'feature.title': 'لماذا تختارنا',
    'feature.subtitle': 'رعاية عالمية المستوى ، تميز بأسعار معقولة - كل ذلك في وجهة واحدة.',
    'feature.1.title': 'متخصصون خبراء',
    'feature.1.desc': 'أطباء معتمدون مع خبرة دولية.',
    'feature.2.title': 'مرافق حديثة',
    'feature.2.desc': 'معدات وتكنولوجيا متطورة.',
    'feature.3.title': 'الدقة والفن',
    'feature.3.desc': 'تصميمات جمالية مصممة خصيصًا لميزاتك الفريدة.',
    'feature.4.title': 'باقات شاملة',
    'feature.4.desc': 'العلاج والإقامة والنقل متضمنة.',

    // Home Treatments Section
    'home.treatments.title': 'علاجاتنا المميزة',
    'home.treatments.subtitle': 'اكتشف الإجراءات الأكثر طلبًا لدينا، والتي يثق بها المرضى من أكثر من 50 دولة',
    
    // Testimonials
    'testimonials.title': 'آراء مرضانا',
    'testimonials.1.text': 'تجربة رائعة! كان الطاقم محترفًا والنتائج فاقت توقعاتي. أوصي بشدة!',
    'testimonials.1.name': 'أحمد علي',
    'testimonials.1.treatment': 'زراعة الأسنان',
    'testimonials.2.text': 'أفضل قرار اتخذته. كان الأطباء مهتمين والعيادة نظيفة جدًا.',
    'testimonials.2.name': 'فاطمة حسن',
    'testimonials.2.treatment': 'قشور الأسنان',
    'testimonials.3.text': 'نتائج زراعة الشعر لا تصدق! مظهر طبيعي وعملية غير مؤلمة. شكرًا!',
    'testimonials.3.name': 'محمد خالد',
    'testimonials.3.treatment': 'زراعة FUE',
    'testimonials.subtitle': 'آلاف المرضى يثقون بنا كل عام',

    // Home Results
    'home.results.title': 'نتائج حقيقية، قصص حقيقية',
    'home.results.subtitle': 'اختبر تحول مرضانا. نحن نفخر بتقديم نتائج طبيعية وعالية الجودة تغير الحياة.',
    'home.results.cta': 'عرض جميع قصص التحول',
    'home.results.1.label': 'تصميم الابتسامة الرقمي',
    'home.results.1.title': 'ابتسامة تغير الحياة',
    'home.results.1.text': 'كنت دائماً أشعر بالخجل من ابتسامتي. استخدم الفريق في Gravity Clinic أحدث تقنيات التصميم الرقمي ليروني ابتسامتي المستقبلية قبل أن نبدأ. النتيجة أفضل مما تخيلت.',
    'home.results.1.category': 'تجميل الأسنان',
    'home.results.1.patient': 'المريضة: سارة م.',
    'home.results.2.label': 'استعادة الشعر بتقنية Soft-FUE',
    'home.results.2.title': 'خط الشعر الطبيعي استعاد عافيته',
    'home.results.2.text': 'كان اختيار Gravity Clinic لزراعة شعري أفضل قرار اتخذته. كانت تقنية FUE غير مؤلمة، وكان التعافي سريعاً بشكل ملحوظ. بعد ستة أشهر، يبدو شعري طبيعياً تماماً.',
    'home.results.2.category': 'زراعة الشعر',
    'home.results.2.patient': 'المريض: جيمس ل.',
    
    // Home CTA
    'home.cta.title': 'هل أنت مستعد لتغيير حياتك؟',
    'home.cta.subtitle': 'احجز استشارتك المجانية اليوم واكتشف الفرق',

    // Dental Treatments
    'dental.title': 'علاجات الأسنان',
    'dental.subtitle': 'رعاية أسنان شاملة بأحدث التقنيات',
    'dental.implants': 'زراعة الأسنان',
    'dental.implants.desc': 'حل دائم لاستبدال الأسنان بزراعات التيتانيوم.',
    'dental.implants.price': 'تواصل معنا للتسعير',
    'dental.whitening': 'تبييض الأسنان',
    'dental.whitening.desc': 'تبييض احترافي لابتسامة أكثر إشراقًا.',
    'dental.whitening.price': 'تواصل معنا للتسعير',
    'dental.veneers': 'قشور البورسلين / إيماكس',
    'dental.veneers.desc': 'حوّل ابتسامتك بقشور مخصصة واستمتع بابتسامة هوليوود.',
    'dental.veneers.price': 'تواصل معنا للتسعير',
    'dental.braces': 'تيجان الزركونيا',
    'dental.braces.desc': 'تيجان عالية المتانة والمظهر الطبيعي للترميم التجميلي.',
    'dental.braces.price': 'تواصل معنا للتسعير',
    'dental.crowns': 'اللومينير',
    'dental.crowns.desc': 'قشور رقيقة جداً لتعزيز ابتسامة سلسة ومتألقة.',
    'dental.crowns.price': 'تواصل معنا للتسعير',
    'dental.rootcanal': 'علاج الجذور',
    'dental.rootcanal.desc': 'علاج قناة الجذر بدون ألم لإنقاذ سنك طبيعياً.',
    'dental.rootcanal.price': 'اتصل بنا للحصول على الأسعار',

    // Dental Treatment Keys (Used in Dental.tsx)
    'dental.treatment.implants.title': 'زراعة الأسنان',
    'dental.treatment.implants.desc': 'حل دائم لاستبدال الأسنان باستخدام غرسات التيتانيوم وتيجان مخصصة.',
    'dental.treatment.whitening.title': 'تبييض الأسنان',
    'dental.treatment.whitening.desc': 'تبييض احترافي لابتسامة مشرقة وواثقة باستخدام تقنية الليزر المتقدمة.',
    'dental.treatment.veneers.title': 'قشور البورسلان / إيماكس',
    'dental.treatment.veneers.desc': 'حوّل ابتسامتك مع الفينير المخصص وتصميم ابتسامة هوليوود.',
    'dental.treatment.braces.title': 'تيجان الزركونيا',
    'dental.treatment.braces.desc': 'تيجان عالية المتانة وذات مظهر طبيعي للترميم الجمالي.',
    'dental.treatment.crowns.title': 'لومينير',
    'dental.treatment.crowns.desc': 'قشور فائقة الرقة لتحسين الابتسامة بشكل سلس.',
    'dental.treatment.rootcanal.title': 'علاج الجذور',
    'dental.treatment.rootcanal.desc': 'علاج قناة الجذر بدون ألم لإنقاذ سنك الطبيعي.',

    // Dental Features
    'dental.f.implants.1': 'زراعات التيتانيوم',
    'dental.f.implants.2': 'ضمان مدى الحياة',
    'dental.f.implants.3': 'إجراء بدون ألم',
    'dental.f.implants.4': 'مظهر طبيعي',
    'dental.f.whitening.1': 'درجة احترافية',
    'dental.f.whitening.2': 'نتائج فورية',
    'dental.f.whitening.3': 'آمن على المينا',
    'dental.f.whitening.4': '8-10 درجات أفتح',
    'dental.f.veneers.1': 'بورسلين مخصص',
    'dental.f.veneers.2': 'مقاوم للبقع',
    'dental.f.veneers.3': 'عمر افتراضي 15-20 سنة',
    'dental.f.veneers.4': 'محاذاة مثالية',
    'dental.f.braces.1': 'خيارات معدنية أو سيراميك',
    'dental.f.braces.2': 'تعديلات منتظمة',
    'dental.f.braces.3': 'علاج 12-24 شهر',
    'dental.f.braces.4': 'خطط دفع متاحة',
    'dental.f.crowns.1': 'زركونيا أو بورسلين',
    'dental.f.crowns.2': 'تطابق مثالي للألوان',
    'dental.f.crowns.3': 'مواد متينة',
    'dental.f.crowns.4': 'إجراء في زيارتين',
    'dental.f.rootcanal.1': 'الحفاظ على السن الطبيعي',
    'dental.f.rootcanal.2': 'مجاهر متطورة',
    'dental.f.rootcanal.3': 'علاج بدون ألم',
    'dental.f.rootcanal.4': 'نسبة نجاح عالية',
    
    // Hair Treatments
    'hair.title': 'استعادة الشعر',
    'hair.subtitle': 'تقنيات زراعة الشعر المتقدمة لنتائج طبيعية',
    'hair.fue': 'زراعة الشعر للرجال',
    'hair.fue.desc': 'نقل الشعر الصحي إلى المناطق الصلعاء تحت التخدير الموضعي.',
    'hair.fue.price': 'تواصل معنا للتسعير',
    'hair.dhi': 'زراعة DHI',
    'hair.dhi.desc': 'زراعة مباشرة للشعر لوضع دقيق.',
    'hair.dhi.price': 'تواصل معنا للتسعير',
    'hair.sapphire': 'FUE الياقوت',
    'hair.sapphire.desc': 'FUE متقدمة بشفرات الياقوت.',
    'hair.sapphire.price': 'تواصل معنا للتسعير',
    'hair.prp': 'علاج PRP',
    'hair.prp.desc': 'علاج البلازما الغنية بالصفائح الدموية.',
    'hair.prp.price': 'تواصل معنا للتسعير',
    'hair.beard': 'زراعة اللحية',
    'hair.beard.desc': 'احصل على لحية أكثر كثافة ووضوحًا.',
    'hair.beard.price': 'تواصل معنا للتسعير',
    'hair.eyebrow': 'زراعة الحواجب',
    'hair.eyebrow.desc': 'استعادة الحواجب بمظهر طبيعي.',
    'hair.eyebrow.price': 'اتصل بنا للحصول على الأسعار',

    // Hair Treatment Keys (Used in Hair.tsx)
    'hair.treatment.fue.title': 'زراعة الشعر بتقنية FUE',
    'hair.treatment.fue.desc': 'اقتطاف وحدات البصيلات للحصول على نتائج طبيعية وأقصى كثافة للشعر.',
    'hair.treatment.dhi.title': 'زراعة الشعر بتقنية DHI',
    'hair.treatment.dhi.desc': 'زراعة الشعر المباشرة لوضع دقيق وتعافي أسرع.',
    'hair.treatment.sapphire.title': 'زراعة الشعر بالسفير (Sapphire FUE)',
    'hair.treatment.sapphire.desc': 'تقنية FUE المتقدمة باستخدام شفرات السفير لتقليل الصدمات والشفاء السريع.',
    'hair.treatment.prp.title': 'علاج PRP',
    'hair.treatment.prp.desc': 'العلاج بالبلازما الغنية بالصفائح الدموية لتحفيز بصيلات الشعر ونموها.',
    'hair.treatment.beard.title': 'زراعة اللحية',
    'hair.treatment.beard.desc': 'احصل على لحية ممتلئة وأكثر تحديداً مع اقتطاف دقيق.',
    'hair.treatment.eyebrow.title': 'زراعة الحواجب',
    'hair.treatment.eyebrow.desc': 'استعادة الحواجب بمظهر طبيعي باستخدام تقنيات الاقتطاف الدقيق المتقدمة.',

    // Hair Features
    'hair.f.fue.1': '3000-5000 بصيلة',
    'hair.f.fue.2': 'بدون ندبات مرئية',
    'hair.f.fue.3': 'تصميم طبيعي لخط الشعر',
    'hair.f.fue.4': 'تدخل جراحي طفيف',
    'hair.f.dhi.1': 'أقلام تشوي (Choi)',
    'hair.f.dhi.2': 'أقصى كثافة',
    'hair.f.dhi.3': 'أقل تداول للبصيلات',
    'hair.f.dhi.4': 'لا حاجة لشقوق جراحية',
    'hair.f.sapphire.1': 'تقنية شفرة السفير',
    'hair.f.sapphire.2': 'شفاء أسرع',
    'hair.f.sapphire.3': 'صدمات أقل للأنسجة',
    'hair.f.sapphire.4': 'اقتطاف عالي الدقة',
    'hair.f.prp.1': 'عوامل نمو طبيعية',
    'hair.f.prp.2': 'غير جراحي',
    'hair.f.prp.3': '3-6 جلسات موصى بها',
    'hair.f.prp.4': 'شعر أكثر كثافة',
    'hair.f.beard.1': '1500-3000 بصيلة',
    'hair.f.beard.2': 'شكل مخصص',
    'hair.f.beard.3': 'اتجاه طبيعي',
    'hair.f.beard.4': 'نتائج دائمة',
    'hair.f.eyebrow.1': '300-800 بصيلة',
    'hair.f.eyebrow.2': 'قوس طبيعي',
    'hair.f.eyebrow.3': 'وضع دقيق',
    'hair.f.eyebrow.4': 'تحسين دقيق',

    // Hair Why
    'hair.why.1.title': 'جراحون خبراء',
    'hair.why.1.desc': 'أكثر من 15 عاماً من الخبرة في استعادة الشعر',
    'hair.why.2.title': 'تقنيات متقدمة',
    'hair.why.2.desc': 'أحدث طرق FUE و DHI والسفير',
    'hair.why.3.title': 'نتائج طبيعية',
    'hair.why.3.desc': 'نسبة نجاح تفوق 95% مع نتائج دائمة',
    
    // Doctors
    'doctors.title': 'تعرف على فريقنا الطبي',
    'doctors.subtitle': 'متخصصون دوليون مكرسون لرعايتك',
    
    // Booking
    'booking.title': 'احجز استشارتك',
    'booking.step1': 'المعلومات الشخصية',
    'booking.step2': 'اختيار العلاج',
    'booking.step3': 'التاريخ المفضل',
    'booking.step4': 'التأكيد',
    'booking.firstName': 'الاسم الأول',
    'booking.lastName': 'اسم العائلة',
    'booking.email': 'البريد الإلكتروني',
    'booking.phone': 'رقم الهاتف',
    'booking.country': 'الدولة',
    'booking.treatment': 'اختر العلاج',
    'booking.date': 'التاريخ المفضل',
    'booking.message': 'معلومات إضافية',
    'booking.next': 'التالي',
    'booking.previous': 'السابق',
    'booking.submit': 'إرسال الحجز',
    
    // Contact
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'نحن هنا للإجابة على أسئلتك',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.name': 'اسمك',
    'contact.subject': 'الموضوع',
    'contact.send': 'إرسال',
    'contact.locations': 'مواقعنا',
    'contact.faq': 'الأسئلة الشائعة',
    'contact.about': 'تعتبر عيادة جرافيتي وجهة رائدة في اسطنبول متخصصة في علاجات الأسنان المتقدمة وزراعة الشعر. يلتزم فريقنا من الخبراء بتقديم رعاية شخصية باستخدام أحدث التقنيات لتحقيق نتائج تغير الحياة.',
    
    // Common
    'common.learnMore': 'اعرف المزيد',
    'common.bookNow': 'احجز الآن',
    'common.readMore': 'اقرأ المزيد',
    'common.viewAll': 'عرض الكل',
    'common.features': 'المميزات',
    'common.pricing': 'الأسعار',
    'common.gallery': 'المعرض',
    'common.years': 'سنوات الخبرة',
    'common.patients': 'مريض',
    'common.viewProfile': 'عرض الملف الشخصي',
    'common.education': 'التعليم والخبرة',
    'common.languages': 'اللغات',
    'common.successRate': 'نسبة النجاح',
    'common.viewDetails': 'عرض التفاصيل',
    'common.whatsappSupport': 'الدعم عبر واتساب',
    'common.patientSatisfaction': 'رضا المرضى',
    'common.successfulResults': 'نتائج ناجحة',
    'common.duration': 'المدة',
    'common.procedure': 'الإجراء',
    'common.appointments': 'المواعيد',
    'common.oneDay': 'يوم واحد',
    'common.hours': 'ساعات',

    // Hero Badge
    'hero.clinic.badge': 'عيادة دولية معتمدة من JCI',

    // Doctors
    'doctors.sarah.specialty': 'كبير جراحي الأسنان',
    'doctors.sarah.bio': 'جراح أسنان معتمد متخصص في زراعة الأسنان وتجميل الأسنان. خريجة كلية هارفارد لطب الأسنان.',
    'doctors.michael.specialty': 'أخصائي تقويم الأسنان',
    'doctors.michael.bio': 'خبير في تقويم الأسنان الحديث مع التركيز على التقويم الشفاف وطرق العلاج السريعة.',
    'doctors.ahmed.specialty': 'جراح زراعة الشعر',
    'doctors.ahmed.bio': 'رائد في تقنيات FUE و DHI مع آلاف عمليات زراعة الشعر الناجحة. متحدث ومدرب دولي.',
    'doctors.emily.specialty': 'طبيبة تجميل أسنان',
    'doctors.emily.bio': 'شغوفة بابتكار ابتسامات جميلة من خلال إجراءات تجميلية متقدمة وتقنيات طفيفة التوغل.',
    'doctors.mehmet.specialty': 'خبير استعادة الشعر',
    'doctors.mehmet.bio': 'متخصص في تصميم خط الشعر الطبيعي والزراعة عالية الكثافة. عضو في ISHRS.',
    'doctors.lisa.specialty': 'أخصائية علاج الجذور',
    'doctors.lisa.bio': 'خبيرة في علاج قناة الجذر وإدارة الألم باستخدام أحدث التقنيات المجهرية.',

    // Booking
    'booking.hero.subtitle': 'رحلتك نحو نسخة أفضل من نفسك تبدأ بخطوة واحدة.',
    'booking.step1.desc': 'يرجى مشاركة تفاصيل الاتصال الخاصة بك للتنسيق الخاص.',
    'booking.step2.desc': 'حدد التخصص الذي تهتم به.',
    'booking.step3.desc': 'اختر نافذة الوصول المفضلة لديك.',
    'booking.step4.desc': 'تحقق من معلوماتك قبل الإنهاء.',
    'booking.success.title': 'تم استلام الحجز',
    'booking.success.desc': 'شكراً لك يا {name}. سيتصل بك فريق رعاية المرضى لدينا في غضون 2-4 ساعات عمل.',

    // Contact
    'contact.info.title': 'تواصل معنا',
    'contact.info.desc': 'لديك أسئلة؟ فريقنا الودود هنا للمساعدة.',
    'contact.faq.subtitle': 'أسئلة شائعة حول رحلاتنا الطبية الفاخرة',
    'contact.workingHours': 'ساعات العمل',
    'contact.monSat': 'الأثنين - السبت',
    'contact.sunday': 'الأحد',
    'contact.closed': 'مغلق',

    // Articles
    'articles.hero.badge': 'الطب القائم على البراهين',
    'articles.hero.subtitle': 'رؤى الخبراء والأدلة السريرية المنسقة من قبل كبار المتخصصين في العالم.',
    'articles.filter.all': 'المجلد: الكل',
    'articles.filter.dental': 'التخصص: الأسنان',
    'articles.filter.hair': 'التخصص: الشعر',
    'articles.newsletter.badge': 'وصول خاص',
    'articles.newsletter.title': 'احصل على الدقة في بريدك الوارد',
    'articles.newsletter.subtitle': 'انضم إلى أكثر من 5000 مريض يتلقون نصائح سريرية شهرية وعلاجات متطورة من متخصصينا.',
    'articles.newsletter.cta': 'انضم إلى القائمة الحصرية',
    
    // Common
    'common.restoration': 'استعادة',
    'footer.expertise': 'خبرتنا',
    'footer.navigation': 'التنقل',
    'footer.contact': 'اتصل بنا',
    'footer.desc': 'وضع المعايير العالمية في السياحة الطبية الفاخرة. الدقة والفن والابتكار في كل إجراء.',
    'footer.whatsapp': 'واتساب / هاتف',
    'footer.istanbul': 'مكتب اسطنبول',
    'footer.address': 'نيشانتاشي، تشويقية رقم 42',
    'footer.hours': 'ساعات العمل',
    'footer.monSat': 'الاثنين - السبت',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.copyright': '© 2026 عيادة جرافيتي العالمية. يتم إجراء جميع الإجراءات من قبل مهنيين طبيين معتمدين.',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};